title: SenhasD | Password generator in javascript
description: A simple vanilla javascript password generator.
theme: minima
markdown: kramdown
highlighter: rouge
baseurl: "/" 
url: "https://SenhasD.github.io"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
